import type { InputHTMLAttributes, TextareaHTMLAttributes } from "react";

import { ImageUrlField } from "@/components/dashboard/media/ImageUrlField";
import { updateConstructSiteSettingsAction } from "@/lib/actions/construct-site-settings.actions";
import { requireActiveConstructContext } from "@/lib/auth/construct-context";
import { ensureConstructSiteSettingsDefaults } from "@/lib/services/construct-site-settings.service";
import { getConstructMediaPickerData } from "@/lib/services/construct-media-picker.service";

const control = "mt-1.5 w-full rounded-md border border-slate-300 bg-white px-3.5 py-2.5 text-sm outline-none focus:border-[#7D9D76] focus:ring-4 focus:ring-[#7D9D76]/25 disabled:bg-slate-100";
const Hint = ({ children }: { children: React.ReactNode }) => <span className="mt-1 block text-xs font-normal text-slate-500">{children}</span>;
function Field({ label, hint, ...props }: { label: string; hint?: string } & InputHTMLAttributes<HTMLInputElement>) { return <label className="block text-sm font-semibold text-slate-700">{label}{hint && <Hint>{hint}</Hint>}<input {...props} className={control} /></label>; }
function Area({ label, hint, ...props }: { label: string; hint?: string } & TextareaHTMLAttributes<HTMLTextAreaElement>) { return <label className="block text-sm font-semibold text-slate-700">{label}{hint && <Hint>{hint}</Hint>}<textarea {...props} className={`${control} min-h-28 resize-y`} /></label>; }
function Section({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <section className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="mb-5"><h2 className="text-lg font-bold text-slate-950">{title}</h2><p className="mt-1 text-sm text-slate-500">{description}</p></div>{children}</section>; }

export default async function SiteSettingsPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const context = await requireActiveConstructContext();
  const [s, { images, folders }] = await Promise.all([
    ensureConstructSiteSettingsDefaults(context.organizationId),
    getConstructMediaPickerData(context.organizationId),
  ]);
  const { saved, error } = await searchParams;
  const disabled = context.role === "VIEWER";
  return (
    <div className="px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
      <header className="mb-6"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#7D9D76]">Website CMS</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">Site settings</h1><p className="mt-2 text-sm text-slate-600">Manage the identity and core website content for {context.organization.name}.</p></header>
      {saved && <p className="mb-5 rounded-md border border-[#7D9D76]/40 bg-[#eef3ec] p-3 text-sm text-[#7D9D76]">Site settings saved successfully.</p>}
      {error && <p className="mb-5 rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
      <form action={updateConstructSiteSettingsAction} className="space-y-5">
        <Section title="Company identity" description="Public company name, positioning and brand assets."><div className="grid gap-4 md:grid-cols-2"><Field label="Company name" name="companyName" defaultValue={s.companyName} required minLength={2} maxLength={100} disabled={disabled} hint="Shown in the header, footer and browser tab. 2–100 characters." /><Field label="Tagline" name="tagline" defaultValue={s.tagline} required minLength={2} maxLength={160} disabled={disabled} hint="A short line shown near the company name. 2–160 characters." /><div className="md:col-span-2"><Area label="Company description" name="description" defaultValue={s.description} required minLength={10} maxLength={2000} disabled={disabled} hint="Used as the default page description for search engines and social sharing. 10–2,000 characters." /></div><ImageUrlField label="Logo URL" name="logoUrl" defaultValue={s.logoUrl} disabled={disabled} hint="A direct link to the logo image shown in the header. Must be a valid URL. Optional." images={images} folders={folders} /><ImageUrlField label="Favicon URL" name="faviconUrl" defaultValue={s.faviconUrl} disabled={disabled} hint="The small icon shown in browser tabs. Must be a valid URL. Optional." images={images} folders={folders} /></div></Section>
        <Section title="Contact and address" description="Information displayed on contact surfaces."><div className="grid gap-4 md:grid-cols-2"><Field label="Email" name="email" type="email" defaultValue={s.email} required disabled={disabled} hint="Shown in the footer and contact page. Must be a valid email address." /><Field label="Phone" name="phone" defaultValue={s.phone} maxLength={40} disabled={disabled} hint="Shown in the footer and contact page. Up to 40 characters. Optional." /><Field label="WhatsApp" name="whatsApp" defaultValue={s.whatsApp ?? ""} maxLength={40} disabled={disabled} hint="Include the country code. Up to 40 characters. Optional — powers a WhatsApp chat link." /><Field label="Website URL" name="website" type="url" defaultValue={s.website ?? ""} disabled={disabled} hint="Your public site address, used as the canonical URL. Must be a valid URL. Optional." /><Field label="Address line 1" name="addressLine1" defaultValue={s.addressLine1} maxLength={160} disabled={disabled} hint="Street address shown in the footer and contact page. Up to 160 characters." /><Field label="Address line 2" name="addressLine2" defaultValue={s.addressLine2 ?? ""} maxLength={160} disabled={disabled} hint="Suite, floor or landmark. Up to 160 characters. Optional." /><Field label="City" name="city" defaultValue={s.city} maxLength={80} disabled={disabled} hint="Up to 80 characters." /><Field label="State" name="state" defaultValue={s.state ?? ""} maxLength={80} disabled={disabled} hint="Up to 80 characters. Optional." /><Field label="Country" name="country" defaultValue={s.country} required minLength={2} maxLength={80} disabled={disabled} hint="2–80 characters." /><Field label="Postal code" name="postalCode" defaultValue={s.postalCode ?? ""} maxLength={20} disabled={disabled} hint="Up to 20 characters. Optional." /><div className="md:col-span-2"><Field label="Google Maps URL" name="googleMapsUrl" type="url" defaultValue={s.googleMapsUrl ?? ""} disabled={disabled} hint="Link to your location on Google Maps, shown on the contact page. Must be a valid URL. Optional." /></div></div></Section>
        <Section title="Homepage hero" description="Primary message visitors see when they arrive."><div className="grid gap-4"><Field label="Hero title" name="heroTitle" defaultValue={s.heroTitle} required minLength={5} maxLength={160} disabled={disabled} hint="The large headline shown at the top of the homepage. 5–160 characters." /><Area label="Hero subtitle" name="heroSubtitle" defaultValue={s.heroSubtitle} required minLength={5} maxLength={400} disabled={disabled} hint="Supporting text shown below the hero title. 5–400 characters." /><ImageUrlField label="Hero image URL" name="heroImageUrl" defaultValue={s.heroImageUrl} disabled={disabled} hint="Background or feature image for the hero section. Must be a valid URL. Optional — a stock photo shows otherwise." images={images} folders={folders} /></div></Section>
        <Section title="Call to action" description="The conversion section displayed across the website."><div className="grid gap-4 md:grid-cols-2"><Field label="CTA title" name="ctaTitle" defaultValue={s.ctaTitle} required minLength={3} maxLength={160} disabled={disabled} hint="Headline for the call-to-action section shown across the site. 3–160 characters." /><Field label="Button text" name="ctaButtonText" defaultValue={s.ctaButtonText} required minLength={2} maxLength={60} disabled={disabled} hint="Label on the call-to-action button, e.g. &quot;Get a Quote&quot;. 2–60 characters." /><div className="md:col-span-2"><Area label="CTA subtitle" name="ctaSubtitle" defaultValue={s.ctaSubtitle} required minLength={5} maxLength={400} disabled={disabled} hint="Supporting text shown below the CTA title. 5–400 characters." /></div><Field label="Button link" name="ctaButtonLink" defaultValue={s.ctaButtonLink} required minLength={1} maxLength={300} disabled={disabled} hint="Where the CTA button leads, e.g. /contact or a full URL. 1–300 characters." /></div></Section>
        <Section title="Company statistics" description="Headline figures displayed on the homepage."><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Field label="Projects completed" name="projectsCompleted" type="number" min="0" max="100000" step="1" defaultValue={s.projectsCompleted} disabled={disabled} hint="Whole number, 0–100,000." /><Field label="Clients served" name="clientsServed" type="number" min="0" max="100000" step="1" defaultValue={s.clientsServed} disabled={disabled} hint="Whole number, 0–100,000." /><Field label="Years experience" name="yearsExperience" type="number" min="0" max="500" step="1" defaultValue={s.yearsExperience} disabled={disabled} hint="Whole number, 0–500." /><Field label="Employees" name="employees" type="number" min="0" max="100000" step="1" defaultValue={s.employees} disabled={disabled} hint="Whole number, 0–100,000." /></div></Section>
        <Section title="About, mission and vision" description="Core company story used on the About page."><div className="grid gap-4 md:grid-cols-2"><Field label="About title" name="aboutTitle" defaultValue={s.aboutTitle ?? ""} maxLength={160} disabled={disabled} hint="Headline for the About page. Up to 160 characters. Optional." /><Field label="About subtitle" name="aboutSubtitle" defaultValue={s.aboutSubtitle ?? ""} maxLength={400} disabled={disabled} hint="Supporting text below the About title. Up to 400 characters. Optional." /><div className="md:col-span-2"><Area label="Company story" name="aboutStory" defaultValue={s.aboutStory ?? ""} maxLength={5000} disabled={disabled} hint="Longer narrative shown on the About page. Up to 5,000 characters. Optional." /></div><Field label="Mission title" name="missionTitle" defaultValue={s.missionTitle ?? ""} maxLength={160} disabled={disabled} hint="Up to 160 characters. Optional." /><Field label="Vision title" name="visionTitle" defaultValue={s.visionTitle ?? ""} maxLength={160} disabled={disabled} hint="Up to 160 characters. Optional." /><Area label="Mission description" name="missionDescription" defaultValue={s.missionDescription ?? ""} maxLength={2000} disabled={disabled} hint="Up to 2,000 characters. Optional." /><Area label="Vision description" name="visionDescription" defaultValue={s.visionDescription ?? ""} maxLength={2000} disabled={disabled} hint="Up to 2,000 characters. Optional." /><div className="md:col-span-2"><ImageUrlField label="About image URL" name="aboutImageUrl" defaultValue={s.aboutImageUrl} disabled={disabled} hint="Image shown alongside the company story. Must be a valid URL. Optional." images={images} folders={folders} /></div></div></Section>
        <Section title="Social profiles" description="Optional footer and contact links."><div className="grid gap-4 md:grid-cols-2"><Field label="Facebook URL" name="facebook" type="url" defaultValue={s.facebook ?? ""} disabled={disabled} hint="Optional — shown as a footer icon. Must be a valid URL." /><Field label="Instagram URL" name="instagram" type="url" defaultValue={s.instagram ?? ""} disabled={disabled} hint="Optional — shown as a footer icon. Must be a valid URL." /><Field label="LinkedIn URL" name="linkedin" type="url" defaultValue={s.linkedin ?? ""} disabled={disabled} hint="Optional — shown as a footer icon. Must be a valid URL." /><Field label="YouTube URL" name="youtube" type="url" defaultValue={s.youtube ?? ""} disabled={disabled} hint="Optional — shown as a footer icon. Must be a valid URL." /><Field label="X / Twitter URL" name="twitter" type="url" defaultValue={s.twitter ?? ""} disabled={disabled} hint="Optional — shown as a footer icon. Must be a valid URL." /></div></Section>
        {!disabled && <div className="sticky bottom-4 flex justify-end rounded-lg border border-slate-200 bg-white/95 p-4 shadow-lg backdrop-blur"><button className="rounded-md bg-[#094136] px-6 py-3 text-sm font-semibold text-white hover:bg-[#7D9D76]">Save site settings</button></div>}
      </form>
    </div>
  );
}
