import type { InputHTMLAttributes, TextareaHTMLAttributes } from "react";

import { updateConstructSiteSettingsAction } from "@/lib/actions/construct-site-settings.actions";
import { requireActiveConstructContext } from "@/lib/auth/construct-context";
import { getConstructPrisma } from "@/lib/construct-prisma";

const control = "mt-1.5 w-full rounded-xl border border-slate-300 bg-white px-3.5 py-2.5 text-sm outline-none focus:border-teal-600 focus:ring-4 focus:ring-teal-100 disabled:bg-slate-100";
function Field({ label, ...props }: { label: string } & InputHTMLAttributes<HTMLInputElement>) { return <label className="block text-sm font-semibold text-slate-700">{label}<input {...props} className={control} /></label>; }
function Area({ label, ...props }: { label: string } & TextareaHTMLAttributes<HTMLTextAreaElement>) { return <label className="block text-sm font-semibold text-slate-700">{label}<textarea {...props} className={`${control} min-h-28 resize-y`} /></label>; }
function Section({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="mb-5"><h2 className="text-lg font-bold text-slate-950">{title}</h2><p className="mt-1 text-sm text-slate-500">{description}</p></div>{children}</section>; }

export default async function SiteSettingsPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const context = await requireActiveConstructContext();
  const s = await getConstructPrisma().siteSettings.findUnique({ where: { organizationId: context.organizationId } });
  if (!s) throw new Error("Site settings have not been provisioned.");
  const { saved, error } = await searchParams;
  const disabled = context.role === "VIEWER";
  return (
    <div className="px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
      <header className="mb-6"><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-700">Website CMS</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">Site settings</h1><p className="mt-2 text-sm text-slate-600">Manage the identity and core website content for {context.organization.name}.</p></header>
      {saved && <p className="mb-5 rounded-xl border border-teal-200 bg-teal-50 p-3 text-sm text-teal-800">Site settings saved successfully.</p>}
      {error && <p className="mb-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
      <form action={updateConstructSiteSettingsAction} className="space-y-5">
        <Section title="Company identity" description="Public company name, positioning and brand assets."><div className="grid gap-4 md:grid-cols-2"><Field label="Company name" name="companyName" defaultValue={s.companyName} required disabled={disabled} /><Field label="Tagline" name="tagline" defaultValue={s.tagline} required disabled={disabled} /><div className="md:col-span-2"><Area label="Company description" name="description" defaultValue={s.description} required disabled={disabled} /></div><Field label="Logo URL" name="logoUrl" type="url" defaultValue={s.logoUrl ?? ""} disabled={disabled} /><Field label="Favicon URL" name="faviconUrl" type="url" defaultValue={s.faviconUrl ?? ""} disabled={disabled} /></div></Section>
        <Section title="Contact and address" description="Information displayed on contact surfaces."><div className="grid gap-4 md:grid-cols-2"><Field label="Email" name="email" type="email" defaultValue={s.email} required disabled={disabled} /><Field label="Phone" name="phone" defaultValue={s.phone} disabled={disabled} /><Field label="WhatsApp" name="whatsApp" defaultValue={s.whatsApp ?? ""} disabled={disabled} /><Field label="Website URL" name="website" type="url" defaultValue={s.website ?? ""} disabled={disabled} /><Field label="Address line 1" name="addressLine1" defaultValue={s.addressLine1} disabled={disabled} /><Field label="Address line 2" name="addressLine2" defaultValue={s.addressLine2 ?? ""} disabled={disabled} /><Field label="City" name="city" defaultValue={s.city} disabled={disabled} /><Field label="State" name="state" defaultValue={s.state ?? ""} disabled={disabled} /><Field label="Country" name="country" defaultValue={s.country} required disabled={disabled} /><Field label="Postal code" name="postalCode" defaultValue={s.postalCode ?? ""} disabled={disabled} /><div className="md:col-span-2"><Field label="Google Maps URL" name="googleMapsUrl" type="url" defaultValue={s.googleMapsUrl ?? ""} disabled={disabled} /></div></div></Section>
        <Section title="Homepage hero" description="Primary message visitors see when they arrive."><div className="grid gap-4"><Field label="Hero title" name="heroTitle" defaultValue={s.heroTitle} required disabled={disabled} /><Area label="Hero subtitle" name="heroSubtitle" defaultValue={s.heroSubtitle} required disabled={disabled} /><Field label="Hero image URL" name="heroImageUrl" type="url" defaultValue={s.heroImageUrl ?? ""} disabled={disabled} /></div></Section>
        <Section title="Call to action" description="The conversion section displayed across the website."><div className="grid gap-4 md:grid-cols-2"><Field label="CTA title" name="ctaTitle" defaultValue={s.ctaTitle} required disabled={disabled} /><Field label="Button text" name="ctaButtonText" defaultValue={s.ctaButtonText} required disabled={disabled} /><div className="md:col-span-2"><Area label="CTA subtitle" name="ctaSubtitle" defaultValue={s.ctaSubtitle} required disabled={disabled} /></div><Field label="Button link" name="ctaButtonLink" defaultValue={s.ctaButtonLink} required disabled={disabled} /></div></Section>
        <Section title="Company statistics" description="Headline figures displayed on the homepage."><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Field label="Projects completed" name="projectsCompleted" type="number" min="0" defaultValue={s.projectsCompleted} disabled={disabled} /><Field label="Clients served" name="clientsServed" type="number" min="0" defaultValue={s.clientsServed} disabled={disabled} /><Field label="Years experience" name="yearsExperience" type="number" min="0" defaultValue={s.yearsExperience} disabled={disabled} /><Field label="Employees" name="employees" type="number" min="0" defaultValue={s.employees} disabled={disabled} /></div></Section>
        <Section title="About, mission and vision" description="Core company story used on the About page."><div className="grid gap-4 md:grid-cols-2"><Field label="About title" name="aboutTitle" defaultValue={s.aboutTitle ?? ""} disabled={disabled} /><Field label="About subtitle" name="aboutSubtitle" defaultValue={s.aboutSubtitle ?? ""} disabled={disabled} /><div className="md:col-span-2"><Area label="Company story" name="aboutStory" defaultValue={s.aboutStory ?? ""} disabled={disabled} /></div><Field label="Mission title" name="missionTitle" defaultValue={s.missionTitle ?? ""} disabled={disabled} /><Field label="Vision title" name="visionTitle" defaultValue={s.visionTitle ?? ""} disabled={disabled} /><Area label="Mission description" name="missionDescription" defaultValue={s.missionDescription ?? ""} disabled={disabled} /><Area label="Vision description" name="visionDescription" defaultValue={s.visionDescription ?? ""} disabled={disabled} /><div className="md:col-span-2"><Field label="About image URL" name="aboutImageUrl" type="url" defaultValue={s.aboutImageUrl ?? ""} disabled={disabled} /></div></div></Section>
        <Section title="Social profiles" description="Optional footer and contact links."><div className="grid gap-4 md:grid-cols-2"><Field label="Facebook URL" name="facebook" type="url" defaultValue={s.facebook ?? ""} disabled={disabled} /><Field label="Instagram URL" name="instagram" type="url" defaultValue={s.instagram ?? ""} disabled={disabled} /><Field label="LinkedIn URL" name="linkedin" type="url" defaultValue={s.linkedin ?? ""} disabled={disabled} /><Field label="YouTube URL" name="youtube" type="url" defaultValue={s.youtube ?? ""} disabled={disabled} /><Field label="X / Twitter URL" name="twitter" type="url" defaultValue={s.twitter ?? ""} disabled={disabled} /></div></Section>
        {!disabled && <div className="sticky bottom-4 flex justify-end rounded-2xl border border-slate-200 bg-white/95 p-4 shadow-lg backdrop-blur"><button className="rounded-xl bg-[#0E4A7B] px-6 py-3 text-sm font-semibold text-white hover:bg-[#0A365A]">Save site settings</button></div>}
      </form>
    </div>
  );
}
