import type { Project, ProjectGalleryItem, ProjectHighlight } from "@prisma/construct-client";
import { saveConstructProjectAction } from "@/lib/actions/construct-project.actions";
type FullProject = Project & { highlights: ProjectHighlight[]; galleryItems: ProjectGalleryItem[] };
const input = "mt-1.5 w-full rounded-xl border border-slate-300 px-3.5 py-2.5 text-sm outline-none focus:border-teal-600 focus:ring-4 focus:ring-teal-100";
const Label = ({ text, children, wide = false }: { text: string; children: React.ReactNode; wide?: boolean }) => <label className={`text-sm font-semibold text-slate-700 ${wide ? "md:col-span-2" : ""}`}>{text}{children}</label>;
export function ProjectForm({ project, error }: { project?: FullProject; error?: string }) { return <form action={saveConstructProjectAction} className="space-y-5">{project && <input type="hidden" name="id" value={project.id} />}{error && <p className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
  <section className="grid gap-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm md:grid-cols-2"><Label text="Title"><input className={input} name="title" defaultValue={project?.title} required /></Label><Label text="Slug"><input className={input} name="slug" defaultValue={project?.slug} required /></Label><Label text="Category"><input className={input} name="category" defaultValue={project?.category} required /></Label><Label text="Status"><input className={input} name="status" placeholder="ONGOING or COMPLETED" defaultValue={project?.status ?? "ONGOING"} required /></Label><Label text="Client"><input className={input} name="client" defaultValue={project?.client} /></Label><Label text="Location"><input className={input} name="location" defaultValue={project?.location} /></Label><Label text="Year"><input className={input} type="number" name="year" min="1800" max="2200" defaultValue={project?.year ?? new Date().getFullYear()} required /></Label><Label text="Duration"><input className={input} name="duration" defaultValue={project?.duration} /></Label><Label text="Budget"><input className={input} name="budget" defaultValue={project?.budget} /></Label><Label text="Area"><input className={input} name="area" defaultValue={project?.area} /></Label><Label text="Cover image URL" wide><input className={input} type="url" name="coverImageUrl" defaultValue={project?.coverImageUrl ?? ""} /></Label><Label text="Description" wide><textarea className={`${input} min-h-44`} name="description" defaultValue={project?.description} required /></Label><label className="flex items-center gap-2 text-sm font-semibold text-slate-700"><input type="checkbox" name="displayFeatured" defaultChecked={project?.featured} />Feature this project</label></section>
  <section className="grid gap-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm md:grid-cols-2"><div><h2 className="font-bold">Project highlights</h2><p className="text-xs text-slate-500">One highlight per line.</p><textarea className={`${input} min-h-44`} name="highlights" defaultValue={project?.highlights.sort((a,b)=>a.sortOrder-b.sortOrder).map(x=>x.text).join("\n")} /></div><div><h2 className="font-bold">Gallery image URLs</h2><p className="text-xs text-slate-500">One absolute image URL per line.</p><textarea className={`${input} min-h-44`} name="galleryUrls" defaultValue={project?.galleryItems.sort((a,b)=>a.sortOrder-b.sortOrder).map(x=>x.imageUrl).join("\n")} /></div></section>
  <section className="grid gap-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm md:grid-cols-2"><h2 className="font-bold md:col-span-2">SEO</h2><Label text="SEO title"><input className={input} name="seoTitle" defaultValue={project?.seoTitle ?? ""} /></Label><Label text="Canonical URL"><input className={input} type="url" name="canonicalUrl" defaultValue={project?.canonicalUrl ?? ""} /></Label><Label text="SEO description" wide><textarea className={`${input} min-h-24`} name="seoDescription" defaultValue={project?.seoDescription ?? ""} /></Label><Label text="Keywords" wide><input className={input} name="seoKeywords" defaultValue={project?.seoKeywords ?? ""} /></Label></section>
  <div className="flex justify-end"><button className="rounded-xl bg-[#0E4A7B] px-6 py-3 text-sm font-semibold text-white">{project ? "Save changes" : "Create project"}</button></div></form>; }
