import { Activity, Building2, Globe2, Radio } from "lucide-react";

import { ConfirmActionButton } from "@/components/dashboard/settings/ConfirmActionButton";
import { ProductAccessCard } from "@/components/dashboard/settings/ProductAccessCard";
import { addConstructDomainAction, makeConstructDomainPrimaryAction, removeConstructDomainAction, updateConstructPublicationAction, updateConstructWorkspaceAction, verifyConstructDomainAction } from "@/lib/actions/construct-settings.actions";
import { requireActiveConstructContext } from "@/lib/auth/construct-context";
import { getConstructPrisma } from "@/lib/construct-prisma";
import { getConstructPlanUsage } from "@/lib/control/construct-subscription.service";

export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const context = await requireActiveConstructContext(); const query = await searchParams; const canAdmin = context.role === "OWNER" || context.role === "ADMIN"; const prisma = getConstructPrisma();
  const [publication, domains, audit, usage] = await Promise.all([prisma.sitePublication.findUnique({ where: { organizationId: context.organizationId } }), prisma.domain.findMany({ where: { organizationId: context.organizationId }, orderBy: [{ isPrimary: "desc" }, { createdAt: "asc" }] }), prisma.auditLog.findMany({ where: { organizationId: context.organizationId }, orderBy: { createdAt: "desc" }, take: 20 }), getConstructPlanUsage(context.organizationId)]);
  const cnameTarget = process.env.CONSTRUCT_CNAME_TARGET ?? "construct.shaoor-ai.com";
  return <div className="px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><header className="mb-6"><p className="text-xs font-bold uppercase tracking-[.2em] text-teal-700">Workspace administration</p><h1 className="mt-2 text-3xl font-bold">Settings</h1><p className="mt-2 text-sm text-slate-600">Manage workspace identity, publishing, domains and access status.</p></header>{query.saved && <p className="mb-5 rounded-xl border border-teal-200 bg-teal-50 p-3 text-sm text-teal-800">Settings updated successfully.</p>}{query.error && <p className="mb-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{query.error}</p>}
    <div className="grid gap-5 xl:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><Building2 className="size-5 text-teal-700"/><h2 className="font-bold">Workspace identity</h2></div><form action={updateConstructWorkspaceAction} className="space-y-4"><label className="grid gap-1.5 text-sm font-semibold">Workspace name<input name="name" defaultValue={context.organization.name} disabled={!canAdmin} className="rounded-xl border border-slate-300 px-3 py-2.5 font-normal disabled:bg-slate-100"/></label><label className="grid gap-1.5 text-sm font-semibold">Workspace slug<input value={context.organization.slug} readOnly className="rounded-xl border border-slate-300 bg-slate-100 px-3 py-2.5 font-normal"/><span className="text-xs font-normal text-slate-500">The slug is permanent because it forms the default site address.</span></label>{canAdmin && <button className="rounded-xl bg-[#0E4A7B] px-4 py-2.5 text-sm font-semibold text-white">Save workspace</button>}</form></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><Radio className="size-5 text-teal-700"/><h2 className="font-bold">Publication</h2></div><p className="text-sm text-slate-600">Current state: <strong>{publication?.status ?? "DRAFT"}</strong></p>{publication?.publishedAt && <p className="mt-1 text-xs text-slate-500">Last published {publication.publishedAt.toLocaleString()}</p>}{canAdmin && <form action={updateConstructPublicationAction} className="mt-4 flex flex-wrap gap-2"><button name="status" value="PUBLISHED" className="rounded-lg bg-teal-700 px-3 py-2 text-sm font-semibold text-white">Publish</button><button name="status" value="UNPUBLISHED" className="rounded-lg border border-amber-300 px-3 py-2 text-sm font-semibold text-amber-700">Unpublish</button><button name="status" value="DRAFT" className="rounded-lg border px-3 py-2 text-sm font-semibold">Return to draft</button></form>}</section>
      <ProductAccessCard usage={usage} workspaceStatus={context.organization.status} role={context.role}/>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><Globe2 className="size-5 text-teal-700"/><h2 className="font-bold">Add custom domain</h2></div><p className="mb-4 text-xs leading-5 text-slate-500">Add the hostname, then create a CNAME pointing to <strong>{cnameTarget}</strong>. A unique TXT verification record will appear below.</p>{canAdmin && <form action={addConstructDomainAction} className="flex gap-2"><input required name="hostname" placeholder="www.customer.com" className="min-w-0 flex-1 rounded-xl border border-slate-300 px-3 py-2.5 text-sm"/><button className="rounded-xl bg-[#0E4A7B] px-4 py-2.5 text-sm font-semibold text-white">Add</button></form>}</section></div>
    <section className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-bold">Domains</h2></div><div className="divide-y">{domains.map(domain => <div key={domain.id} className="p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{domain.hostname}</p>{domain.isPrimary && <span className="rounded-full bg-teal-50 px-2 py-0.5 text-xs font-bold text-teal-700">Primary</span>}<span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs font-bold text-slate-600">{domain.status}</span></div>{!domain.hostname.endsWith(".construct.shaoor-ai.com") && domain.status !== "ACTIVE" && <div className="mt-3 rounded-lg bg-slate-50 p-3 text-xs text-slate-600"><p><strong>TXT host:</strong> _shaoor-verify.{domain.hostname}</p><p className="mt-1 break-all"><strong>TXT value:</strong> {domain.verificationToken}</p><p className="mt-1"><strong>CNAME:</strong> {domain.hostname} → {cnameTarget}</p></div>}</div>{canAdmin && <div className="flex flex-wrap gap-2">{!domain.hostname.endsWith(".construct.shaoor-ai.com") && domain.status !== "ACTIVE" && <form action={verifyConstructDomainAction}><input type="hidden" name="id" value={domain.id}/><button className="rounded-lg border px-3 py-1.5 text-xs font-semibold">Verify DNS</button></form>}{domain.status === "ACTIVE" && !domain.isPrimary && <form action={makeConstructDomainPrimaryAction}><input type="hidden" name="id" value={domain.id}/><button className="rounded-lg border px-3 py-1.5 text-xs font-semibold">Make primary</button></form>}{!domain.isPrimary && domain.hostname !== `${context.organization.slug}.construct.shaoor-ai.com` && <form action={removeConstructDomainAction}><input type="hidden" name="id" value={domain.id}/><ConfirmActionButton message={`Remove ${domain.hostname} from this workspace?`} className="rounded-lg border border-red-200 px-3 py-1.5 text-xs font-semibold text-red-700">Remove</ConfirmActionButton></form>}</div>}</div></div>)}</div></section>
    <section className="mt-5 rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-2 border-b p-5"><Activity className="size-5 text-teal-700"/><h2 className="font-bold">Recent activity</h2></div>{audit.length === 0 ? <p className="p-5 text-sm text-slate-500">No activity recorded.</p> : <div className="divide-y">{audit.map(item => <div key={item.id} className="flex items-start justify-between gap-4 p-4"><div><p className="text-sm font-semibold">{item.title}</p><p className="mt-1 text-xs uppercase text-slate-400">{item.module} · {item.action}</p></div><time className="shrink-0 text-xs text-slate-400">{item.createdAt.toLocaleString()}</time></div>)}</div>}</section>
  </div>;
}
