import Link from "next/link";
import { ArrowLeft, Mail, Phone } from "lucide-react";
import { notFound } from "next/navigation";

import { updateConstructMessageStatusAction } from "@/lib/actions/construct-message.actions";
import { requireActiveConstructContext } from "@/lib/auth/construct-context";
import { getConstructPrisma } from "@/lib/construct-prisma";

export default async function MessageDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ updated?: string }> }) {
  const context = await requireActiveConstructContext(); const { id } = await params; const query = await searchParams;
  const message = await getConstructPrisma().contactMessage.findFirst({ where: { id, organizationId: context.organizationId } }); if (!message) notFound(); const canUpdate = context.role !== "VIEWER";
  return <div className="px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><Link href="/dashboard/messages" className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-teal-700"><ArrowLeft className="size-4"/>Back to enquiries</Link>{query.updated && <p className="mb-5 rounded-xl border border-teal-200 bg-teal-50 p-3 text-sm text-teal-800">Enquiry status updated.</p>}
    <article className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header className="border-b p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold text-slate-600">{message.status}</span><time className="text-xs text-slate-400">{message.createdAt.toLocaleString()}</time></div><h1 className="mt-3 text-2xl font-bold">{message.subject || `Enquiry from ${message.name}`}</h1><p className="mt-1 text-sm text-slate-600">{message.name}</p></div>{canUpdate && <form action={updateConstructMessageStatusAction} className="flex gap-2"><input type="hidden" name="id" value={message.id}/><select name="status" defaultValue={message.status} className="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="NEW">New</option><option value="READ">Read</option><option value="REPLIED">Replied</option><option value="ARCHIVED">Archived</option></select><button className="rounded-lg bg-[#0E4A7B] px-3 py-2 text-sm font-semibold text-white">Update</button></form>}</div></header>
      <div className="grid gap-6 p-5 lg:grid-cols-[1fr_280px]"><div><h2 className="text-xs font-bold uppercase tracking-wider text-slate-500">Message</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-slate-700">{message.message}</p></div><aside className="space-y-4 rounded-xl bg-slate-50 p-4"><div><p className="text-xs font-bold uppercase text-slate-400">Email</p><a href={`mailto:${message.email}?subject=${encodeURIComponent(`Re: ${message.subject || "Your enquiry"}`)}`} className="mt-1 inline-flex items-center gap-2 break-all text-sm font-semibold text-teal-700"><Mail className="size-4"/>{message.email}</a></div>{message.phone && <div><p className="text-xs font-bold uppercase text-slate-400">Phone</p><a href={`tel:${message.phone}`} className="mt-1 inline-flex items-center gap-2 text-sm font-semibold text-teal-700"><Phone className="size-4"/>{message.phone}</a></div>}{message.projectInterest && <div><p className="text-xs font-bold uppercase text-slate-400">Service interest</p><p className="mt-1 text-sm">{message.projectInterest}</p></div>}<div><p className="text-xs font-bold uppercase text-slate-400">Consent recorded</p><p className="mt-1 text-sm">{message.consentAt ? message.consentAt.toLocaleString() : "Not recorded"}</p></div></aside></div>
    </article></div>;
}
