import "server-only";

import { getConstructPrisma } from "@/lib/construct-prisma";
import { resolvePublicConstructOrganization } from "@/lib/construct-public-tenant";
import { prisma as legacyPrisma } from "@/lib/prisma";
import { getSiteSettings } from "@/lib/settings";

export type PublicSiteSettings = Awaited<ReturnType<typeof getSiteSettings>>;

export type PublicService = { id: string | number; title: string; slug: string; shortDescription: string; description: string; image: string | null; icon: string | null; displayOrder: number; isActive: boolean; seoTitle: string | null; seoDescription: string | null; seoKeywords: string | null; canonicalUrl: string | null; createdAt: Date; updatedAt: Date };
export type PublicProject = { id: string | number; slug: string; title: string; category: string; status: string; client: string; location: string; year: number; duration: string; budget: string; area: string; coverImage: string | null; description: string; featured: boolean; seoTitle: string | null; seoDescription: string | null; seoKeywords: string | null; canonicalUrl: string | null; createdAt: Date; updatedAt: Date; gallery: Array<{ id: string | number; image: string; altText?: string | null }>; highlights: Array<{ id: string | number; text: string }> };
export type PublicTeamMember = { id: string | number; name: string; slug: string; designation: string; shortBio: string; photo: string; email: string | null; phone: string | null; linkedin: string | null; instagram: string | null; twitter: string | null; displayOrder: number; showOnHomepage: boolean; isActive: boolean; seoTitle: string | null; seoDescription: string | null; seoKeywords: string | null; canonicalUrl: string | null; createdAt: Date; updatedAt: Date };
export type PublicClient = { id: string | number; name: string; slug: string; logo: string | null; website: string | null; category: string | null; description: string | null; displayOrder: number; featured: boolean; active: boolean };
export type PublicTestimonial = { id: string | number; clientName: string; company: string | null; designation: string | null; photo: string | null; rating: number; testimonial: string; projectName: string | null; featured: boolean; active: boolean; displayOrder: number };
export type PublicFaq = { id: string | number; question: string; answer: string; category: string | null; displayOrder: number; featured: boolean; active: boolean };

function mapService(item: { id: string; title: string; slug: string; shortDescription: string; description: string; imageUrl: string | null; icon: string | null; displayOrder: number; isActive: boolean; seoTitle: string | null; seoDescription: string | null; seoKeywords: string | null; canonicalUrl: string | null; createdAt: Date; updatedAt: Date }): PublicService { return { ...item, image: item.imageUrl }; }
function mapProject(item: { id: string; slug: string; title: string; category: string; status: string; client: string; location: string; year: number; duration: string; budget: string; area: string; coverImageUrl: string | null; description: string; featured: boolean; seoTitle: string | null; seoDescription: string | null; seoKeywords: string | null; canonicalUrl: string | null; createdAt: Date; updatedAt: Date; galleryItems: Array<{ id: string; imageUrl: string; altText: string | null }>; highlights: Array<{ id: string; text: string }> }): PublicProject { return { ...item, coverImage: item.coverImageUrl, gallery: item.galleryItems.map(image => ({ id: image.id, image: image.imageUrl, altText: image.altText })) }; }

export async function getPublicSiteSettings(): Promise<PublicSiteSettings> {
  const organization = await resolvePublicConstructOrganization();
  if (!organization) return getSiteSettings();
  const settings = await getConstructPrisma().siteSettings.findUnique({ where: { organizationId: organization.id } });
  if (!settings) throw new Error("Tenant site settings are missing.");
  return {
    id: 0, companyId: 0, companyName: settings.companyName, tagline: settings.tagline, description: settings.description, logo: settings.logoUrl, favicon: settings.faviconUrl,
    phone: settings.phone, email: settings.email, website: settings.website, addressLine1: settings.addressLine1, addressLine2: settings.addressLine2, city: settings.city, state: settings.state, country: settings.country, postalCode: settings.postalCode,
    facebook: settings.facebook, instagram: settings.instagram, linkedin: settings.linkedin, youtube: settings.youtube, twitter: settings.twitter,
    heroTitle: settings.heroTitle, heroSubtitle: settings.heroSubtitle, heroImage: settings.heroImageUrl, ctaTitle: settings.ctaTitle, ctaSubtitle: settings.ctaSubtitle, ctaButtonText: settings.ctaButtonText, ctaButtonLink: settings.ctaButtonLink,
    projectsCompleted: settings.projectsCompleted, clientsServed: settings.clientsServed, yearsExperience: settings.yearsExperience, employees: settings.employees,
    seoTitle: "", seoDescription: "", seoKeywords: "", whatsApp: settings.whatsApp, googleMapsUrl: settings.googleMapsUrl, aboutTitle: settings.aboutTitle, aboutSubtitle: settings.aboutSubtitle, aboutStory: settings.aboutStory,
    missionTitle: settings.missionTitle, missionDescription: settings.missionDescription, visionTitle: settings.visionTitle, visionDescription: settings.visionDescription, aboutImage: settings.aboutImageUrl,
    createdAt: settings.createdAt, updatedAt: settings.updatedAt,
  };
}

export async function getPublicServices() {
  const organization = await resolvePublicConstructOrganization();
  if (!organization) return legacyPrisma.service.findMany({ where: { isActive: true }, orderBy: { displayOrder: "asc" } });
  const items = await getConstructPrisma().service.findMany({ where: { organizationId: organization.id, isActive: true }, orderBy: { displayOrder: "asc" } }); return items.map(mapService);
}
export async function getPublicServiceBySlug(slug: string) { const organization = await resolvePublicConstructOrganization(); if (!organization) return legacyPrisma.service.findFirst({ where: { slug } }); const item = await getConstructPrisma().service.findFirst({ where: { organizationId: organization.id, slug } }); return item ? mapService(item) : null; }
export async function getRelatedPublicServices(id: string | number, take = 3) { const organization = await resolvePublicConstructOrganization(); if (!organization) return legacyPrisma.service.findMany({ where: { isActive: true, id: { not: Number(id) } }, orderBy: { displayOrder: "asc" }, take }); const items = await getConstructPrisma().service.findMany({ where: { organizationId: organization.id, isActive: true, id: { not: String(id) } }, orderBy: { displayOrder: "asc" }, take }); return items.map(mapService); }

export async function getPublicProjects(filters?: { status?: string; featured?: boolean; category?: string; take?: number }) {
  const organization = await resolvePublicConstructOrganization();
  if (!organization) return legacyPrisma.project.findMany({ where: { ...(filters?.status ? { status: filters.status } : {}), ...(filters?.featured !== undefined ? { featured: filters.featured } : {}), ...(filters?.category ? { category: filters.category } : {}) }, include: { gallery: { orderBy: { id: "asc" } }, highlights: { orderBy: { id: "asc" } } }, orderBy: { year: "desc" }, take: filters?.take });
  const items = await getConstructPrisma().project.findMany({ where: { organizationId: organization.id, ...(filters?.status ? { status: filters.status } : {}), ...(filters?.featured !== undefined ? { featured: filters.featured } : {}), ...(filters?.category ? { category: filters.category } : {}) }, include: { galleryItems: { orderBy: { sortOrder: "asc" } }, highlights: { orderBy: { sortOrder: "asc" } } }, orderBy: { year: "desc" }, take: filters?.take }); return items.map(mapProject);
}
export async function getPublicProjectBySlug(slug: string) { const projects = await getPublicProjects(); return projects.find(project => project.slug === slug) ?? null; }
export async function getRelatedPublicProjects(project: PublicProject, take = 3) { const projects = await getPublicProjects({ category: project.category }); return projects.filter(item => item.id !== project.id).slice(0, take); }

export async function getPublicTeamMembers() { const organization = await resolvePublicConstructOrganization(); if (!organization) return legacyPrisma.teamMember.findMany({ where: { isActive: true }, orderBy: { displayOrder: "asc" } }); const items = await getConstructPrisma().teamMember.findMany({ where: { organizationId: organization.id, isActive: true }, orderBy: { displayOrder: "asc" } }); return items.map(item => ({ ...item, photo: item.photoUrl })) satisfies PublicTeamMember[]; }
export async function getPublicClients(filters?: { featured?: boolean; take?: number }): Promise<PublicClient[]> { const organization = await resolvePublicConstructOrganization(); if (!organization) return legacyPrisma.client.findMany({ where: { active: true, ...(filters?.featured !== undefined ? { featured: filters.featured } : {}) }, orderBy: { displayOrder: "asc" }, take: filters?.take }); const items = await getConstructPrisma().client.findMany({ where: { organizationId: organization.id, isActive: true, ...(filters?.featured !== undefined ? { featured: filters.featured } : {}) }, orderBy: [{ displayOrder: "asc" }, { name: "asc" }], take: filters?.take }); return items.map(item => ({ ...item, logo: item.logoUrl, active: item.isActive })); }
export async function getPublicTestimonials(filters?: { featured?: boolean; take?: number }): Promise<PublicTestimonial[]> { const organization = await resolvePublicConstructOrganization(); if (!organization) return legacyPrisma.testimonial.findMany({ where: { active: true, ...(filters?.featured !== undefined ? { featured: filters.featured } : {}) }, orderBy: { displayOrder: "asc" }, take: filters?.take }); const items = await getConstructPrisma().testimonial.findMany({ where: { organizationId: organization.id, isActive: true, ...(filters?.featured !== undefined ? { featured: filters.featured } : {}) }, orderBy: [{ displayOrder: "asc" }, { clientName: "asc" }], take: filters?.take }); return items.map(item => ({ ...item, photo: item.photoUrl, active: item.isActive })); }
export async function getPublicFaqs(filters?: { featured?: boolean; take?: number }): Promise<PublicFaq[]> { const organization = await resolvePublicConstructOrganization(); if (!organization) return legacyPrisma.fAQ.findMany({ where: { active: true, ...(filters?.featured !== undefined ? { featured: filters.featured } : {}) }, orderBy: { displayOrder: "asc" }, take: filters?.take }); const items = await getConstructPrisma().faq.findMany({ where: { organizationId: organization.id, isActive: true, ...(filters?.featured !== undefined ? { featured: filters.featured } : {}) }, orderBy: [{ displayOrder: "asc" }, { question: "asc" }], take: filters?.take }); return items.map(item => ({ ...item, active: item.isActive })); }
export async function getPublicStats() { const organization = await resolvePublicConstructOrganization(); if (!organization) return Promise.all([legacyPrisma.project.count({ where: { status: "Completed" } }), legacyPrisma.client.count({ where: { active: true } }), legacyPrisma.service.count({ where: { isActive: true } }), legacyPrisma.teamMember.count({ where: { isActive: true } })]); const db = getConstructPrisma(); return Promise.all([db.project.count({ where: { organizationId: organization.id, status: "Completed" } }), db.client.count({ where: { organizationId: organization.id, isActive: true } }), db.service.count({ where: { organizationId: organization.id, isActive: true } }), db.teamMember.count({ where: { organizationId: organization.id, isActive: true } })]); }
