import type { Client, Faq, TeamMember, Testimonial } from "@prisma/construct-client/client";
import { BookOpen, Building2, ImageIcon, ListTree, MessageSquareQuote, Plus, Users } from "lucide-react";
import Image from "next/image";

import { NameSlugFields } from "@/components/dashboard/content/NameSlugFields";
import { StarRatingField } from "@/components/dashboard/content/StarRatingField";
import { ImageUrlField, type PickableImage, type PickerFolder } from "@/components/dashboard/media/ImageUrlField";
import { ConfirmActionButton } from "@/components/dashboard/settings/ConfirmActionButton";
import { deleteConstructContentAction, saveConstructContentAction, toggleConstructContentAction } from "@/lib/actions/construct-content.actions";
import { createConstructProjectTaxonomyAction, deleteConstructProjectTaxonomyAction } from "@/lib/actions/construct-project-taxonomy.actions";
import { requireActiveConstructContext } from "@/lib/auth/construct-context";
import { getConstructPrisma } from "@/lib/construct-prisma";
import { getConstructMediaPickerData } from "@/lib/services/construct-media-picker.service";
import { getConstructProjectTaxonomy } from "@/lib/services/construct-project-taxonomy.service";

const inputClass = "w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:border-[#7D9D76]";
const Hint = ({ children }: { children: React.ReactNode }) => <span className="text-[11px] font-normal normal-case text-slate-500">{children}</span>;
function Field({ label, name, value, type = "text", required = false, min, max, minLength, maxLength, hint }: { label: string; name: string; value?: string | number | null; type?: string; required?: boolean; min?: number; max?: number; minLength?: number; maxLength?: number; hint?: string }) {
  return <label className="grid gap-1 text-xs font-semibold text-slate-600">{label}{hint && <Hint>{hint}</Hint>}<input className={inputClass} name={name} type={type} defaultValue={value ?? ""} required={required} min={min} max={max} minLength={minLength} maxLength={maxLength} /></label>;
}
function Area({ label, name, value, required = false, minLength, maxLength, hint }: { label: string; name: string; value?: string | null; required?: boolean; minLength?: number; maxLength?: number; hint?: string }) {
  return <label className="grid gap-1 text-xs font-semibold text-slate-600 sm:col-span-2">{label}{hint && <Hint>{hint}</Hint>}<textarea className={`${inputClass} min-h-24 resize-y`} name={name} defaultValue={value ?? ""} required={required} minLength={minLength} maxLength={maxLength} /></label>;
}
function Select({ label, name, value, options, required = false, hint, emptyOption }: { label: string; name: string; value?: string | null; options: string[]; required?: boolean; hint?: string; emptyOption?: string }) {
  return <label className="grid gap-1 text-xs font-semibold text-slate-600">{label}{hint && <Hint>{hint}</Hint>}<select className={inputClass} name={name} defaultValue={value ?? ""} required={required && !emptyOption}>{emptyOption ? <option value="">{emptyOption}</option> : <option value="" disabled>{options.length === 0 ? "No clients saved yet" : "Select a client"}</option>}{options.map((option) => <option key={option} value={option}>{option}</option>)}</select></label>;
}
function Check({ label, name, checked = false, hint }: { label: string; name: string; checked?: boolean; hint?: string }) {
  return <label className="flex items-start gap-2 text-sm font-medium text-slate-700"><input name={name} type="checkbox" defaultChecked={checked} className="mt-0.5 size-4 accent-[#7D9D76]" /><span>{label}{hint && <span className="block text-[11px] font-normal normal-case text-slate-500">{hint}</span>}</span></label>;
}
function FormFooter({ kind, id, active, canDelete }: { kind: string; id?: string; active?: boolean; canDelete: boolean }) {
  return <div className="sticky bottom-4 flex flex-wrap items-center gap-2 rounded-lg border border-slate-200 bg-white/95 p-4 shadow-lg backdrop-blur sm:col-span-2"><button className="rounded-lg bg-[#094136] px-4 py-2 text-sm font-semibold text-white">{id ? "Save changes" : "Create item"}</button>{id && <><button formAction={toggleConstructContentAction} className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold">{active ? "Deactivate" : "Activate"}</button>{canDelete && <ConfirmActionButton formAction={deleteConstructContentAction} message="Permanently delete this content item?" className="rounded-lg border border-red-200 px-3 py-2 text-sm font-semibold text-red-700" >Delete</ConfirmActionButton>}</>}<input type="hidden" name="kind" value={kind} />{id && <input type="hidden" name="id" value={id} />}</div>;
}

function TeamForm({ item, canDelete, images, folders }: { item?: TeamMember; canDelete: boolean; images: PickableImage[]; folders?: PickerFolder[] }) {
  return <form action={saveConstructContentAction} className="grid gap-3 border-t border-slate-200 p-4 sm:grid-cols-2"><NameSlugFields nameLabel="Name" isNew={!item} defaultName={item?.name} defaultSlug={item?.slug} inputClassName={inputClass} labelClassName="grid gap-1 text-xs font-semibold text-slate-600" nameMaxLength={120} /><Field label="Designation" name="designation" value={item?.designation} required minLength={2} maxLength={160} hint="Job title shown under their name, e.g. &quot;Lead Architect&quot;. 2–160 characters." /><ImageUrlField label="Photo URL" name="photoUrl" defaultValue={item?.photoUrl} required hint="A direct link to their headshot photo. Must be a valid URL." images={images} folders={folders} labelClassName="grid gap-1 text-xs font-semibold text-slate-600" inputClassName={inputClass} /><Area label="Short biography" name="shortBio" value={item?.shortBio} required minLength={10} maxLength={1000} hint="Shown on the team page under their name. 10–1,000 characters." /><Field label="Email" name="email" value={item?.email} type="email" maxLength={254} hint="Optional — shown publicly if provided." /><Field label="Phone" name="phone" value={item?.phone} maxLength={50} hint="Optional — shown publicly if provided. Up to 50 characters." /><Field label="LinkedIn URL" name="linkedin" value={item?.linkedin} type="url" hint="Optional social link icon on their profile. Must be a valid URL." /><Field label="Instagram URL" name="instagram" value={item?.instagram} type="url" hint="Optional social link icon on their profile. Must be a valid URL." /><Field label="X / Twitter URL" name="twitter" value={item?.twitter} type="url" hint="Optional social link icon on their profile. Must be a valid URL." /><Field label="Display order" name="displayOrder" value={item?.displayOrder ?? 0} type="number" min={0} max={10000} hint="Lower numbers appear first in the team list. Whole number, 0–10,000." /><Check label="Show on homepage" name="showOnHomepage" checked={item?.showOnHomepage ?? true} /><Field label="SEO title" name="seoTitle" value={item?.seoTitle} maxLength={160} hint="Optional — falls back to their name. Up to 160 characters." /><Area label="SEO description" name="seoDescription" value={item?.seoDescription} maxLength={320} hint="Optional — falls back to the short biography. Up to 320 characters." /><Field label="SEO keywords" name="seoKeywords" value={item?.seoKeywords} maxLength={500} hint="Comma-separated terms, up to 500 characters. Optional." /><Field label="Canonical URL" name="canonicalUrl" value={item?.canonicalUrl} type="url" hint="Set only if this content is also published elsewhere. Must be a valid URL. Optional." /><FormFooter kind="team" id={item?.id} active={item?.isActive} canDelete={canDelete} /></form>;
}
function ClientForm({ item, canDelete, images, folders }: { item?: Client; canDelete: boolean; images: PickableImage[]; folders?: PickerFolder[] }) {
  return <form action={saveConstructContentAction} className="grid gap-3 border-t border-slate-200 p-4 sm:grid-cols-2"><NameSlugFields nameLabel="Client name" isNew={!item} defaultName={item?.name} defaultSlug={item?.slug} inputClassName={inputClass} labelClassName="grid gap-1 text-xs font-semibold text-slate-600" nameMaxLength={160} /><ImageUrlField label="Logo URL" name="logoUrl" defaultValue={item?.logoUrl} hint="A direct link to their logo image. Must be a valid URL. Optional." images={images} folders={folders} labelClassName="grid gap-1 text-xs font-semibold text-slate-600" inputClassName={inputClass} /><Field label="Website URL" name="website" value={item?.website} type="url" hint="Optional — makes the logo clickable. Must be a valid URL." /><Field label="Category" name="category" value={item?.category} maxLength={120} hint="e.g. &quot;Real estate&quot; or &quot;Retail&quot;. Up to 120 characters. Optional." /><Field label="Display order" name="displayOrder" value={item?.displayOrder ?? 0} type="number" min={0} max={10000} hint="Lower numbers appear first in the client showcase. Whole number, 0–10,000." /><Area label="Description" name="description" value={item?.description} maxLength={1000} hint="Optional — not usually shown publicly, for internal reference. Up to 1,000 characters." /><Check label="Featured client" name="featured" checked={item?.featured} hint="Shown in the highlighted clients section on the homepage." /><FormFooter kind="client" id={item?.id} active={item?.isActive} canDelete={canDelete} /></form>;
}
function TestimonialForm({ item, canDelete, images, folders, clientNames, projectNames }: { item?: Testimonial; canDelete: boolean; images: PickableImage[]; folders?: PickerFolder[]; clientNames: string[]; projectNames: string[] }) {
  return <form action={saveConstructContentAction} className="grid gap-3 border-t border-slate-200 p-4 sm:grid-cols-2"><Select label="Client name" name="clientName" value={item?.clientName} options={clientNames} required hint="Pick from clients saved in the Clients section above — add the client there first if it isn't listed yet." /><Field label="Company" name="company" value={item?.company} maxLength={160} hint="Optional — shown under their name. Up to 160 characters." /><Field label="Designation" name="designation" value={item?.designation} maxLength={160} hint="Their job title. Up to 160 characters. Optional." /><ImageUrlField label="Photo URL" name="photoUrl" defaultValue={item?.photoUrl} hint="A direct link to their photo. Must be a valid URL. Optional." images={images} folders={folders} labelClassName="grid gap-1 text-xs font-semibold text-slate-600" inputClassName={inputClass} /><Select label="Project name" name="projectName" value={item?.projectName} options={projectNames} emptyOption="General (not project-specific)" hint="Pick the project this quote relates to, or the general option if it isn't about one specific project." /><StarRatingField name="rating" defaultValue={item?.rating ?? 5} hint="Shown as a star rating alongside the quote." /><Area label="Testimonial" name="testimonial" value={item?.testimonial} required minLength={10} maxLength={3000} hint="The quote itself, shown on the homepage and testimonials section. 10–3,000 characters." /><Field label="Display order" name="displayOrder" value={item?.displayOrder ?? 0} type="number" min={0} max={10000} hint="Lower numbers appear first. Whole number, 0–10,000." /><Check label="Featured testimonial" name="featured" checked={item?.featured} hint="Shown in the highlighted testimonials section on the homepage." /><FormFooter kind="testimonial" id={item?.id} active={item?.isActive} canDelete={canDelete} /></form>;
}
function FaqForm({ item, canDelete }: { item?: Faq; canDelete: boolean }) {
  return <form action={saveConstructContentAction} className="grid gap-3 border-t border-slate-200 p-4 sm:grid-cols-2"><Field label="Question" name="question" value={item?.question} required minLength={5} maxLength={500} hint="Shown as the collapsed FAQ heading. 5–500 characters." /><Field label="Category" name="category" value={item?.category} maxLength={120} hint="Optional — used to group related questions. Up to 120 characters." /><Area label="Answer" name="answer" value={item?.answer} required minLength={5} maxLength={5000} hint="Shown when the question is expanded. 5–5,000 characters." /><Field label="Display order" name="displayOrder" value={item?.displayOrder ?? 0} type="number" min={0} max={10000} hint="Lower numbers appear first in the FAQ list. Whole number, 0–10,000." /><Check label="Featured FAQ" name="featured" checked={item?.featured} hint="Shown first, or highlighted, in the FAQ section." /><FormFooter kind="faq" id={item?.id} active={item?.isActive} canDelete={canDelete} /></form>;
}

function Thumbnail({ src, alt }: { src?: string | null; alt: string }) {
  return <div className="grid size-10 shrink-0 place-items-center overflow-hidden rounded-md border border-slate-200 bg-slate-50">{src ? <Image src={src} alt={alt} width={40} height={40} unoptimized className="size-10 object-cover" /> : <ImageIcon className="size-4 text-slate-300" />}</div>;
}
function ItemShell({ title, subtitle, active, imageUrl, children }: { title: string; subtitle: string; active: boolean; imageUrl?: string | null; children: React.ReactNode }) {
  return <details className="overflow-hidden rounded-md border border-slate-200 bg-white"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 p-4"><span className="flex min-w-0 items-center gap-3">{imageUrl !== undefined && <Thumbnail src={imageUrl} alt={title} />}<span className="min-w-0"><span className="font-semibold text-slate-950">{title}</span><span className="ml-2 text-xs text-slate-500">{subtitle}</span></span></span><span className={`shrink-0 rounded-full px-2 py-0.5 text-xs font-semibold ${active ? "bg-[#eef3ec] text-[#7D9D76]" : "bg-slate-100 text-slate-500"}`}>{active ? "Active" : "Inactive"}</span></summary>{children}</details>;
}
function Section({ title, description, icon: Icon, count, addForm, children, canEdit }: { title: string; description: string; icon: typeof Users; count: number; addForm: React.ReactNode; children: React.ReactNode; canEdit: boolean }) {
  return <section className="rounded-lg border border-slate-200 bg-slate-50/70 p-4"><div className="mb-4 flex items-start justify-between gap-4"><div className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-md bg-[#eef3ec] text-[#7D9D76]"><Icon className="size-5" /></span><div><h2 className="font-bold text-slate-950">{title} <span className="text-sm font-medium text-slate-400">({count})</span></h2><p className="text-sm text-slate-600">{description}</p></div></div></div>{canEdit && <details className="mb-3 overflow-hidden rounded-md border border-dashed border-[#7D9D76]/60 bg-white"><summary className="flex cursor-pointer list-none items-center gap-2 p-4 text-sm font-semibold text-[#7D9D76]"><Plus className="size-4" />Add new</summary>{addForm}</details>}<div className="grid gap-2">{children}</div></section>;
}
function TaxonomySection({ title, description, kind, values, canEdit }: { title: string; description: string; kind: "CATEGORY" | "STATUS"; values: string[]; canEdit: boolean }) {
  return <section className="rounded-lg border border-slate-200 bg-slate-50/70 p-4">
    <div className="mb-4 flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-md bg-[#eef3ec] text-[#7D9D76]"><ListTree className="size-5" /></span><div><h2 className="font-bold text-slate-950">{title} <span className="text-sm font-medium text-slate-400">({values.length})</span></h2><p className="text-sm text-slate-600">{description}</p></div></div>
    <div className="mb-3 flex flex-wrap gap-2">
      {values.length === 0
        ? <p className="text-sm text-slate-500">None yet.</p>
        : values.map((value) => (
          <span key={value} className="flex items-center gap-1.5 rounded-full border border-slate-200 bg-white py-1 pl-3 pr-1.5 text-xs font-semibold text-slate-700">
            {value}
            {canEdit && <form action={deleteConstructProjectTaxonomyAction}><input type="hidden" name="kind" value={kind} /><input type="hidden" name="value" value={value} /><ConfirmActionButton message={`Remove "${value}"? Projects already using it keep their value, but it won't be selectable for new ones.`} className="rounded-full px-1.5 py-0.5 text-slate-400 hover:bg-red-50 hover:text-red-700">×</ConfirmActionButton></form>}
          </span>
        ))}
    </div>
    {canEdit && <form action={createConstructProjectTaxonomyAction} className="flex gap-2"><input type="hidden" name="kind" value={kind} /><input name="value" required maxLength={19} placeholder="e.g. RESIDENTIAL" className={`${inputClass} max-w-56 uppercase`} style={{ textTransform: "uppercase" }} /><button className="shrink-0 rounded-lg bg-[#094136] px-3 py-2 text-xs font-semibold text-white">Add</button></form>}
    <p className="mt-2 text-[11px] text-slate-500">Always saved in UPPERCASE, under 20 characters — shown as-is on public project cards.</p>
  </section>;
}

export default async function ContentPage({ searchParams }: { searchParams: Promise<{ saved?: string; deleted?: string; error?: string }> }) {
  const context = await requireActiveConstructContext(); const prisma = getConstructPrisma(); const query = await searchParams;
  const [team, clients, testimonials, faqs, { images, folders }, projects, taxonomy] = await Promise.all([
    prisma.teamMember.findMany({ where: { organizationId: context.organizationId }, orderBy: [{ displayOrder: "asc" }, { name: "asc" }] }),
    prisma.client.findMany({ where: { organizationId: context.organizationId }, orderBy: [{ displayOrder: "asc" }, { name: "asc" }] }),
    prisma.testimonial.findMany({ where: { organizationId: context.organizationId }, orderBy: [{ displayOrder: "asc" }, { clientName: "asc" }] }),
    prisma.faq.findMany({ where: { organizationId: context.organizationId }, orderBy: [{ displayOrder: "asc" }, { question: "asc" }] }),
    getConstructMediaPickerData(context.organizationId),
    prisma.project.findMany({ where: { organizationId: context.organizationId }, orderBy: { title: "asc" }, select: { title: true } }),
    getConstructProjectTaxonomy(context.organizationId),
  ]);
  const clientNames = clients.map((client) => client.name);
  const projectNames = projects.map((project) => project.title);
  const canEdit = context.role !== "VIEWER"; const canDelete = context.role === "OWNER" || context.role === "ADMIN";
  return <div className="px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><header className="mb-6"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#7D9D76]">Website CMS</p><h1 className="mt-2 text-3xl font-bold">Content</h1><p className="mt-2 text-sm text-slate-600">Manage reusable people, customer proof, and help content across the public website.</p></header>
    {(query.saved || query.deleted) && <p className="mb-5 rounded-md border border-[#7D9D76]/40 bg-[#eef3ec] p-3 text-sm text-[#7D9D76]">Content updated successfully.</p>}{query.error && <p className="mb-5 rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">{query.error}</p>}
    {!canEdit && <p className="mb-5 rounded-md border border-blue-200 bg-blue-50 p-3 text-sm text-blue-800">You have read-only access to this content.</p>}
    <div className="grid gap-5">
      <Section title="Leadership profiles" description="People shown on the team and homepage sections." icon={Users} count={team.length} canEdit={canEdit} addForm={<TeamForm canDelete={canDelete} images={images} folders={folders} />}>{team.map(item => <ItemShell key={item.id} title={item.name} subtitle={item.designation} active={item.isActive} imageUrl={item.photoUrl}>{canEdit && <TeamForm item={item} canDelete={canDelete} images={images} folders={folders} />}</ItemShell>)}</Section>
      <Section title="Clients" description="Customer logos and company references." icon={Building2} count={clients.length} canEdit={canEdit} addForm={<ClientForm canDelete={canDelete} images={images} folders={folders} />}>{clients.map(item => <ItemShell key={item.id} title={item.name} subtitle={item.category ?? "Client"} active={item.isActive} imageUrl={item.logoUrl}>{canEdit && <ClientForm item={item} canDelete={canDelete} images={images} folders={folders} />}</ItemShell>)}</Section>
      <Section title="Testimonials" description="Customer quotes used as social proof." icon={MessageSquareQuote} count={testimonials.length} canEdit={canEdit} addForm={<TestimonialForm canDelete={canDelete} images={images} folders={folders} clientNames={clientNames} projectNames={projectNames} />}>{testimonials.map(item => <ItemShell key={item.id} title={item.clientName} subtitle={item.company ?? "Testimonial"} active={item.isActive} imageUrl={item.photoUrl}>{canEdit && <TestimonialForm item={item} canDelete={canDelete} images={images} folders={folders} clientNames={clientNames} projectNames={projectNames} />}</ItemShell>)}</Section>
      <TaxonomySection title="Project categories" description="Options shown in a project's Category field." kind="CATEGORY" values={taxonomy.categories} canEdit={canEdit} />
      <TaxonomySection title="Project statuses" description="Options shown in a project's Status field." kind="STATUS" values={taxonomy.statuses} canEdit={canEdit} />
      <Section title="FAQs" description="Common questions and answers for prospective customers." icon={BookOpen} count={faqs.length} canEdit={canEdit} addForm={<FaqForm canDelete={canDelete} />}>{faqs.map(item => <ItemShell key={item.id} title={item.question} subtitle={item.category ?? "General"} active={item.isActive}>{canEdit && <FaqForm item={item} canDelete={canDelete} />}</ItemShell>)}</Section>
    </div>
  </div>;
}
