import { Pencil, Plus } from "lucide-react";
import Link from "next/link";
import { deleteConstructServiceAction, toggleConstructServiceAction } from "@/lib/actions/construct-service.actions";
import { requireActiveConstructContext } from "@/lib/auth/construct-context";
import { getConstructPrisma } from "@/lib/construct-prisma";

export default async function ServicesPage({ searchParams }: { searchParams: Promise<{ saved?: string; deleted?: string; error?: string }> }) {
  const context = await requireActiveConstructContext();
  const services = await getConstructPrisma().service.findMany({ where: { organizationId: context.organizationId }, orderBy: [{ displayOrder: "asc" }, { title: "asc" }] });
  const query = await searchParams;
  return <div className="px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><header className="mb-6 flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-700">Website CMS</p><h1 className="mt-2 text-3xl font-bold">Services</h1><p className="mt-2 text-sm text-slate-600">Manage the capabilities presented on your website.</p></div>{context.role !== "VIEWER" && <Link href="/dashboard/services/new" className="inline-flex items-center gap-2 rounded-xl bg-[#0E4A7B] px-4 py-2.5 text-sm font-semibold text-white"><Plus className="size-4" />New service</Link>}</header>
    {(query.saved || query.deleted) && <p className="mb-5 rounded-xl border border-teal-200 bg-teal-50 p-3 text-sm text-teal-800">Services updated successfully.</p>}{query.error && <p className="mb-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{query.error}</p>}
    <div className="grid gap-4">{services.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-slate-500">No services yet. Create the first service for this tenant.</div> : services.map((service) => <article key={service.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><h2 className="font-bold text-slate-950">{service.title}</h2><span className={`rounded-full px-2 py-0.5 text-xs font-semibold ${service.isActive ? "bg-teal-50 text-teal-700" : "bg-slate-100 text-slate-500"}`}>{service.isActive ? "Active" : "Inactive"}</span></div><p className="mt-1 text-sm text-slate-600">{service.shortDescription}</p><p className="mt-2 text-xs text-slate-400">/{service.slug} · Order {service.displayOrder}</p></div><div className="flex flex-wrap gap-2">{context.role !== "VIEWER" && <><Link href={`/dashboard/services/${service.id}`} className="inline-flex items-center gap-2 rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold"><Pencil className="size-4" />Edit</Link><form action={toggleConstructServiceAction}><input type="hidden" name="id" value={service.id} /><button className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold">{service.isActive ? "Deactivate" : "Activate"}</button></form></>}{(context.role === "OWNER" || context.role === "ADMIN") && <form action={deleteConstructServiceAction}><input type="hidden" name="id" value={service.id} /><button className="rounded-lg border border-red-200 px-3 py-2 text-sm font-semibold text-red-700">Delete</button></form>}</div></div></article>)}</div>
  </div>;
}
