import { ShieldCheck, UserPlus, Users } from "lucide-react";

import { createConstructInvitationAction, removeConstructMemberAction, revokeConstructInvitationAction, updateConstructMemberRoleAction } from "@/lib/actions/construct-team.actions";
import { requireActiveConstructContext } from "@/lib/auth/construct-context";
import { getConstructPrisma } from "@/lib/construct-prisma";

export default async function TeamPage({ searchParams }: { searchParams: Promise<{ error?: string; updated?: string; invited?: string; role?: string }> }) {
  const context = await requireActiveConstructContext(); const query = await searchParams; const canManage = context.role === "OWNER" || context.role === "ADMIN";
  const prisma = getConstructPrisma();
  const [members, invitations] = await Promise.all([
    prisma.membership.findMany({ where: { organizationId: context.organizationId, status: "ACTIVE" }, include: { user: true }, orderBy: { createdAt: "asc" } }),
    prisma.membership.findMany({ where: { organizationId: context.organizationId, status: "INVITED" }, orderBy: { createdAt: "desc" } }),
  ]);
  return <div className="px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><header className="mb-6"><p className="text-xs font-bold uppercase tracking-[.2em] text-teal-700">Workspace access</p><h1 className="mt-2 text-3xl font-bold">Team</h1><p className="mt-2 text-sm text-slate-600">Control who can access this tenant and what they can manage.</p></header>
    {query.error && <p className="mb-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{query.error}</p>}{query.updated && <p className="mb-5 rounded-xl border border-teal-200 bg-teal-50 p-3 text-sm text-teal-800">Team access updated successfully.</p>}{query.invited && <p className="mb-5 rounded-xl border border-teal-200 bg-teal-50 p-4 text-sm text-teal-900"><strong>{query.invited}</strong> has been invited as {query.role?.toLowerCase()}. Ask them to sign in with this email address (or create an account with it, if they&apos;re new) — they&apos;ll land right in this workspace.</p>}
    {canManage && <form action={createConstructInvitationAction} className="mb-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><UserPlus className="size-5 text-teal-700"/><h2 className="font-bold">Invite a team member</h2></div><div className="grid gap-3 sm:grid-cols-[1fr_180px_auto]"><input required name="email" type="email" placeholder="name@company.com" className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm"/><select name="role" defaultValue="EDITOR" className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm"><option value="EDITOR">Editor</option><option value="VIEWER">Viewer</option>{context.role === "OWNER" && <option value="ADMIN">Admin</option>}</select><button className="rounded-xl bg-[#0E4A7B] px-4 py-2.5 text-sm font-semibold text-white">Invite</button></div></form>}
    <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-2 border-b p-5"><Users className="size-5 text-teal-700"/><h2 className="font-bold">Members ({members.length})</h2></div><div className="divide-y">{members.map(member => <div key={member.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{member.user?.fullName || member.user?.email}{member.userId === context.userId && <span className="ml-2 text-xs text-teal-700">You</span>}</p><p className="text-xs text-slate-500">{member.user?.email}</p></div><div className="flex flex-wrap items-center gap-2">{member.role === "OWNER" ? <span className="inline-flex items-center gap-1 rounded-full bg-amber-50 px-3 py-1 text-xs font-semibold text-amber-700"><ShieldCheck className="size-3.5"/>Owner</span> : canManage ? <><form action={updateConstructMemberRoleAction} className="flex gap-2"><input type="hidden" name="membershipId" value={member.id}/><select name="role" defaultValue={member.role} disabled={context.role === "ADMIN" && member.role === "ADMIN"} className="rounded-lg border border-slate-300 px-2 py-1.5 text-xs"><option value="EDITOR">Editor</option><option value="VIEWER">Viewer</option>{context.role === "OWNER" && <option value="ADMIN">Admin</option>}</select><button disabled={context.role === "ADMIN" && member.role === "ADMIN"} className="rounded-lg border px-3 py-1.5 text-xs font-semibold disabled:opacity-40">Save</button></form>{member.userId !== context.userId && !(context.role === "ADMIN" && member.role === "ADMIN") && <form action={removeConstructMemberAction}><input type="hidden" name="membershipId" value={member.id}/><button className="rounded-lg border border-red-200 px-3 py-1.5 text-xs font-semibold text-red-700">Remove</button></form>}</> : <span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">{member.role}</span>}</div></div>)}</div></section>
    <section className="mt-6 rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-bold">Pending invitations ({invitations.length})</h2></div>{invitations.length === 0 ? <p className="p-6 text-sm text-slate-500">No pending invitations.</p> : <div className="divide-y">{invitations.map(invite => <div key={invite.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{invite.invitedEmail}</p><p className="text-xs text-slate-500">{invite.role} · Invited {invite.createdAt.toLocaleDateString()}</p></div>{canManage && !(context.role === "ADMIN" && invite.role === "ADMIN") && <form action={revokeConstructInvitationAction}><input type="hidden" name="id" value={invite.id}/><button className="rounded-lg border border-red-200 px-3 py-1.5 text-xs font-semibold text-red-700">Revoke</button></form>}</div>)}</div>}</section>
  </div>;
}
