import { ShieldCheck } from "lucide-react";
import type { ConstructPlanUsage } from "@/lib/control/construct-subscription.service";

export function ProductAccessCard({usage,workspaceStatus,role}:{usage:ConstructPlanUsage|null;workspaceStatus:string;role:string}){
 const access=usage?.access;
 return <section className="rounded-2xl border border-slate-200 bg-slate-950 p-5 text-white shadow-sm"><div className="mb-4 flex items-center gap-2"><ShieldCheck className="size-5 text-teal-400"/><h2 className="font-bold">Product access</h2></div><dl className="space-y-3 text-sm"><div className="flex justify-between"><dt className="text-slate-400">Workspace status</dt><dd className="font-semibold">{workspaceStatus}</dd></div><div className="flex justify-between"><dt className="text-slate-400">Your role</dt><dd className="font-semibold">{role}</dd></div><div className="flex justify-between"><dt className="text-slate-400">Commercial plan</dt><dd className={`font-semibold ${access?"text-teal-300":"text-amber-300"}`}>{access?.planName??"Not linked"}</dd></div>{access&&<><div className="flex justify-between"><dt className="text-slate-400">Subscription</dt><dd className="font-semibold">{access.status}</dd></div><div className="flex justify-between"><dt className="text-slate-400">Provisioning</dt><dd className="font-semibold">{access.provisioningStatus}</dd></div>{access.periodEnd&&<div className="flex justify-between"><dt className="text-slate-400">Service end</dt><dd className="font-semibold">{access.periodEnd.toLocaleDateString("en-IN",{timeZone:"UTC"})}</dd></div>}</>}</dl>
 {usage&&<div className="mt-5 border-t border-white/10 pt-5"><h3 className="text-xs font-bold uppercase tracking-wider text-slate-400">Plan usage</h3><div className="mt-4 space-y-4">{usage.items.map(item=>{const percent=Math.min(100,Math.round(item.used/item.limit*100));return <div key={item.featureCode}><div className="mb-1.5 flex justify-between text-xs"><span>{item.label}</span><span className={percent>=90?"text-amber-300":"text-slate-300"}>{item.used} / {item.limit}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/10"><div className={`h-full rounded-full ${percent>=100?"bg-red-400":percent>=90?"bg-amber-400":"bg-teal-400"}`} style={{width:`${percent}%`}}/></div></div>})}<div className="flex justify-between text-xs"><span>Custom domain</span><span className={usage.customDomain?"text-teal-300":"text-slate-400"}>{usage.customDomain?"Included":"Not included"}</span></div></div></div>}
 <p className="mt-4 text-xs leading-5 text-slate-400">{access?`Offline commercial access is controlled by Shaoor AI for ${access.accountName}.`:"This workspace has not yet been linked to a Shaoor Construct subscription."}</p></section>;
}
