export const websiteDesign = {
  container: "mx-auto max-w-7xl px-5 sm:px-8",
  sectionY: "py-16 md:py-24",
  sectionHeaderWrap: "mx-auto mb-12 max-w-3xl text-center md:mb-16",
  sectionEyebrow: "text-sm font-semibold uppercase tracking-[0.25em] text-(--primary)",
  sectionTitle: "mt-3 text-3xl font-bold text-slate-900 md:text-4xl",
  sectionSubtitle: "mx-auto mt-5 max-w-3xl text-base leading-8 text-slate-600 md:text-lg",
  pageHero: "relative overflow-hidden bg-[#094136] text-white",
  pageHeroOverlay: "absolute inset-0 bg-gradient-to-br from-[#094136] via-[#094136]/95 to-[#7D9D76]/80",
  pageHeroInner: "relative z-10 mx-auto max-w-7xl px-5 py-16 sm:px-8 md:py-24",
  pageHeroSubtitle: "text-sm font-semibold uppercase tracking-[0.3em] text-accent",
  pageHeroTitle: "mt-4 text-4xl font-bold tracking-tight text-white md:text-5xl",
  pageHeroDescription: "mt-5 max-w-3xl text-base leading-8 text-slate-200 md:text-lg",
  card: "overflow-hidden rounded-3xl border border-[#dce5da] bg-white shadow-[0_8px_24px_rgba(9,65,54,.07)] transition duration-300 hover:-translate-y-1 hover:border-[#7D9D76]/60 hover:shadow-[0_18px_48px_rgba(9,65,54,.12)]",
  cardBody: "p-6",
  cardTitle: "text-2xl font-bold text-slate-900",
  cardText: "text-slate-600",
  primaryButton: "inline-flex items-center justify-center rounded-xl bg-[#094136] px-8 py-4 font-semibold text-white shadow-sm transition hover:-translate-y-0.5 hover:bg-[#7D9D76] hover:shadow-lg",
  secondaryButton: "inline-flex items-center justify-center rounded-xl border border-[#7D9D76] px-8 py-4 font-semibold text-[#094136] transition hover:bg-[#eef3ec]",
} as const;
