export const websiteDesign = {
  container: "mx-auto max-w-7xl px-6 sm:px-8",
  sectionY: "py-20 md:py-24",
  sectionHeaderWrap: "mx-auto mb-14 max-w-3xl text-center",
  sectionEyebrow: "text-sm font-semibold uppercase tracking-[0.25em] text-(--primary)",
  sectionTitle: "mt-3 text-3xl font-bold text-slate-900 md:text-4xl",
  sectionSubtitle: "mx-auto mt-5 max-w-3xl text-base leading-8 text-slate-600 md:text-lg",
  pageHero: "relative overflow-hidden bg-slate-900 text-white",
  pageHeroOverlay: "absolute inset-0 bg-gradient-to-br from-slate-900 via-slate-900/95 to-[#0E4A7B]/80",
  pageHeroInner: "relative z-10 mx-auto max-w-7xl px-6 py-20 sm:px-8 md:py-24",
  pageHeroSubtitle: "text-sm font-semibold uppercase tracking-[0.3em] text-accent",
  pageHeroTitle: "mt-4 text-4xl font-bold tracking-tight text-white md:text-5xl",
  pageHeroDescription: "mt-5 max-w-3xl text-base leading-8 text-slate-200 md:text-lg",
  card: "overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-lg",
  cardBody: "p-6",
  cardTitle: "text-2xl font-bold text-slate-900",
  cardText: "text-slate-600",
  primaryButton: "inline-flex items-center justify-center rounded-lg bg-[#0E4A7B] px-8 py-4 font-semibold text-white transition hover:bg-[#0A365A]",
  secondaryButton: "inline-flex items-center justify-center rounded-lg border border-slate-300 px-8 py-4 font-semibold text-slate-800 transition hover:bg-slate-100",
} as const;
