import Link from "next/link"; import Image from "next/image"; import { Eye, EyeOff, ImageIcon, Pencil, Plus, Star, Trash2 } from "lucide-react";
import { deleteConstructProjectAction, toggleConstructProjectActiveAction, toggleConstructProjectFeaturedAction } from "@/lib/actions/construct-project.actions"; import { requireActiveConstructContext } from "@/lib/auth/construct-context"; import { getConstructPrisma } from "@/lib/construct-prisma";
function Thumbnail({ src, alt }: { src: string | null; alt: string }) { return <div className="grid size-16 shrink-0 place-items-center overflow-hidden rounded-md border border-slate-200 bg-slate-50">{src ? <Image src={src} alt={alt} width={64} height={64} unoptimized className="size-16 object-cover" /> : <ImageIcon className="size-5 text-slate-300" />}</div>; }
// Every action button shares this exact shape (icon + label, same
// padding/border/font) so the row never looks mismatched regardless of
// label length — that inconsistency is what this replaces.
const actionButton = "inline-flex items-center justify-center gap-1.5 whitespace-nowrap rounded-lg border px-3 py-2 text-sm font-semibold";
export default async function ProjectsPage({ searchParams }: { searchParams: Promise<{ saved?: string; deleted?: string; error?: string }> }) { const context=await requireActiveConstructContext(); const prisma=getConstructPrisma();
  // Raw SQL for is_active: exists in Postgres but the generated client
  // here couldn't be regenerated (dev server holds the query engine
  // binary locked on Windows) — merge it onto the typed rows below
  // until a client regen picks the field up.
  const [projects,activeRows]=await Promise.all([
    prisma.project.findMany({where:{organizationId:context.organizationId},include:{_count:{select:{galleryItems:true,highlights:true}}},orderBy:{updatedAt:"desc"}}),
    prisma.$queryRaw<{id:string;isActive:boolean}[]>`SELECT id, is_active AS "isActive" FROM construct.projects WHERE organization_id = ${context.organizationId}::uuid`,
  ]);
  const activeById=new Map(activeRows.map(r=>[r.id,r.isActive]));
  const q=await searchParams; return <div className="px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><header className="mb-6 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#7D9D76]">Website CMS</p><h1 className="mt-2 text-3xl font-bold">Projects</h1></div>{context.role!=="VIEWER"&&<Link href="/dashboard/projects/new" className="inline-flex items-center gap-2 rounded-md bg-[#094136] px-4 py-2.5 text-sm font-semibold text-white"><Plus className="size-4"/>New project</Link>}</header>{(q.saved||q.deleted)&&<p className="mb-5 rounded-md bg-[#eef3ec] p-3 text-sm text-[#7D9D76]">Projects updated successfully.</p>}{q.error&&<p className="mb-5 rounded-md bg-red-50 p-3 text-sm text-red-700">{q.error}</p>}<div className="grid gap-4">{!projects.length?<div className="rounded-lg border border-dashed border-slate-300 bg-white p-10 text-center text-slate-500">No projects yet.</div>:projects.map(p=>{const isActive=activeById.get(p.id)??true;return <article key={p.id} className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 sm:flex-row sm:justify-between"><div className="flex gap-4"><Thumbnail src={p.coverImageUrl} alt={p.title} /><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold">{p.title}</h2><span className={`rounded-full px-2 py-0.5 text-xs font-semibold ${isActive?"bg-[#eef3ec] text-[#7D9D76]":"bg-red-50 text-red-700"}`}>{isActive?"Visible":"Hidden"}</span>{p.featured&&<span className="rounded-full bg-amber-50 px-2 py-0.5 text-xs font-semibold text-amber-700">Featured</span>}</div><p className="mt-1 text-sm text-slate-600">{p.category} · {p.status} · {p.location}</p><p className="mt-2 text-xs text-slate-400">{p._count.highlights} highlights · {p._count.galleryItems} gallery images</p></div></div><div className="flex flex-wrap gap-2">{context.role!=="VIEWER"&&<><Link className={actionButton} href={`/dashboard/projects/${p.id}`}><Pencil className="size-4"/>Edit</Link><form action={toggleConstructProjectActiveAction}><input type="hidden" name="id" value={p.id}/><button className={actionButton}>{isActive?<><EyeOff className="size-4"/>Hide</>:<><Eye className="size-4"/>Show</>}</button></form><form action={toggleConstructProjectFeaturedAction}><input type="hidden" name="id" value={p.id}/><button className={actionButton}><Star className="size-4"/>{p.featured?"Unfeature":"Feature"}</button></form></>}{(context.role==="OWNER"||context.role==="ADMIN")&&<form action={deleteConstructProjectAction}><input type="hidden" name="id" value={p.id}/><button className={`${actionButton} border-red-200 text-red-700`}><Trash2 className="size-4"/>Delete</button></form>}</div></div></article>;})}</div></div>; }
