import { Globe2, Search } from "lucide-react";

import { updateConstructSeoPageAction, updateConstructSeoSettingsAction } from "@/lib/actions/construct-seo.actions";
import { requireActiveConstructContext } from "@/lib/auth/construct-context";
import { getConstructPrisma } from "@/lib/construct-prisma";
import { ensureConstructSeoDefaults } from "@/lib/services/construct-seo.service";

function Input({ label, name, value, disabled, type = "text", required = false }: { label: string; name: string; value: string | null; disabled: boolean; type?: string; required?: boolean }) { return <label className="grid gap-1.5 text-sm font-semibold text-slate-700">{label}<input name={name} type={type} defaultValue={value ?? ""} disabled={disabled} required={required} className="rounded-xl border border-slate-300 px-3 py-2.5 font-normal disabled:bg-slate-100"/></label>; }
function Area({ label, name, value, disabled, required = false }: { label: string; name: string; value: string | null; disabled: boolean; required?: boolean }) { return <label className="grid gap-1.5 text-sm font-semibold text-slate-700">{label}<textarea name={name} defaultValue={value ?? ""} disabled={disabled} required={required} rows={3} className="rounded-xl border border-slate-300 px-3 py-2.5 font-normal disabled:bg-slate-100"/></label>; }
function Check({ label, name, checked, disabled }: { label: string; name: string; checked: boolean; disabled: boolean }) { return <label className="flex items-center gap-2 text-sm font-semibold text-slate-700"><input name={name} type="checkbox" defaultChecked={checked} disabled={disabled} className="size-4"/>{label}</label>; }

export default async function SeoDashboardPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const context = await requireActiveConstructContext(); await ensureConstructSeoDefaults(context.organizationId); const query = await searchParams; const disabled = context.role === "VIEWER"; const prisma = getConstructPrisma();
  const [settings, pages] = await Promise.all([prisma.seoSettings.findUniqueOrThrow({ where: { organizationId: context.organizationId } }), prisma.seoPage.findMany({ where: { organizationId: context.organizationId }, orderBy: { pageName: "asc" } })]);
  return <div className="px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><header className="mb-6"><p className="text-xs font-bold uppercase tracking-[.2em] text-teal-700">Discoverability</p><h1 className="mt-2 text-3xl font-bold">SEO</h1><p className="mt-2 text-sm text-slate-600">Manage search metadata, social previews, indexing and verification for this tenant.</p></header>{query.saved && <p className="mb-5 rounded-xl border border-teal-200 bg-teal-50 p-3 text-sm text-teal-800">SEO settings saved successfully.</p>}{query.error && <p className="mb-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{query.error}</p>}
    <form action={updateConstructSeoSettingsAction} className="mb-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-5 flex items-center gap-2"><Globe2 className="size-5 text-teal-700"/><h2 className="text-lg font-bold">Global settings</h2></div><div className="grid gap-4 md:grid-cols-2"><Input label="Site name" name="siteName" value={settings.siteName} disabled={disabled} required/><Input label="Canonical site URL" name="siteUrl" type="url" value={settings.siteUrl} disabled={disabled} required/><Input label="Default title" name="defaultTitle" value={settings.defaultTitle} disabled={disabled} required/><Input label="Default keywords" name="defaultKeywords" value={settings.defaultKeywords} disabled={disabled}/><div className="md:col-span-2"><Area label="Default description" name="defaultDescription" value={settings.defaultDescription} disabled={disabled} required/></div><Input label="Default social image URL" name="defaultOgImageUrl" value={settings.defaultOgImageUrl} disabled={disabled}/><Input label="Favicon URL" name="faviconUrl" value={settings.faviconUrl} disabled={disabled}/><Input label="Apple touch icon URL" name="appleTouchIconUrl" value={settings.appleTouchIconUrl} disabled={disabled}/><Input label="Twitter/X handle" name="twitterHandle" value={settings.twitterHandle} disabled={disabled}/><Input label="Facebook App ID" name="facebookAppId" value={settings.facebookAppId} disabled={disabled}/><Input label="Google verification token" name="googleVerification" value={settings.googleVerification} disabled={disabled}/><Input label="Bing verification token" name="bingVerification" value={settings.bingVerification} disabled={disabled}/><div className="flex gap-5 md:col-span-2"><Check label="Allow indexing" name="robotsIndex" checked={settings.robotsIndex} disabled={disabled}/><Check label="Allow link following" name="robotsFollow" checked={settings.robotsFollow} disabled={disabled}/></div></div>{!disabled && <button className="mt-5 rounded-xl bg-[#0E4A7B] px-4 py-2.5 text-sm font-semibold text-white">Save global SEO</button>}</form>
    <div className="space-y-4"><div className="flex items-center gap-2"><Search className="size-5 text-teal-700"/><h2 className="text-lg font-bold">Page metadata</h2></div>{pages.map(page => <details key={page.id} className="rounded-2xl border border-slate-200 bg-white shadow-sm"><summary className="cursor-pointer list-none p-5"><div className="flex items-center justify-between"><div><h3 className="font-bold">{page.pageName}</h3><p className="mt-1 text-xs text-slate-500">{page.pageKey === "home" ? "/" : `/${page.pageKey}`} · {page.robotsIndex ? "Indexable" : "Not indexable"}</p></div><span className="text-sm font-semibold text-teal-700">Edit</span></div></summary><form action={updateConstructSeoPageAction} className="grid gap-4 border-t p-5 md:grid-cols-2"><input type="hidden" name="pageKey" value={page.pageKey}/><Input label="Page title" name="title" value={page.title} disabled={disabled} required/><Input label="Keywords" name="keywords" value={page.keywords} disabled={disabled}/><div className="md:col-span-2"><Area label="Meta description" name="description" value={page.description} disabled={disabled} required/></div><Input label="Canonical URL" name="canonicalUrl" value={page.canonicalUrl} disabled={disabled}/><Input label="Social image URL" name="ogImageUrl" value={page.ogImageUrl} disabled={disabled}/><Input label="Social title" name="ogTitle" value={page.ogTitle} disabled={disabled}/><Input label="Social description" name="ogDescription" value={page.ogDescription} disabled={disabled}/><div className="flex gap-5 md:col-span-2"><Check label="Allow indexing" name="robotsIndex" checked={page.robotsIndex} disabled={disabled}/><Check label="Allow link following" name="robotsFollow" checked={page.robotsFollow} disabled={disabled}/></div>{!disabled && <button className="w-fit rounded-xl bg-[#0E4A7B] px-4 py-2.5 text-sm font-semibold text-white">Save {page.pageName} SEO</button>}</form></details>)}</div>
  </div>;
}
